### ISSUE TITLE
似乎不支持3.0？

### ISSUE THREAD

**Issue by bioinformatist** [Yurunsoft/tdengine-restful-connector#2]
看起来是`taosd`的RESTful接口返回内容变了：

![image](https://user-images.githubusercontent.com/17194719/187144665-b4c1e22f-2315-43a9-9025-462d9e693958.png)

如上图，我是依赖codeception创建了测试代码，在2.6上是可以正确运行的。

翻查了提示信息中对应部分的[源码](https://github.com/Yurunsoft/tdengine-restful-connector/blob/9e095bac63118449b631a1bc6ab1dedfdaf2b7d6/src/Client.php#L69-L72)，发现是处理POST请求的返回值时解析错误。

**Comment by Yurunsoft** [comment]
做了一下兼容，麻烦把 `yurunsoft/tdengine-restful-connector` 版本改为 `dev-tdengine-3.0` 试一下，期待你的反馈~

**Comment by bioinformatist** [comment]
好像没问题啦，我这边测试的时候是这样的：

![image](https://user-images.githubusercontent.com/17194719/187181393-b79d0cca-13c6-44b8-b5a8-f16b6f0fde97.png)

这个是我应用层里的SQL语句还没适配到3.0的语法导致的（之前是2.4，自作孽不可活=。=

谢谢宇大，现在和数据库通讯是正常的，我这周内会把应用层里需要修改语法的地方改好，如果有什么新的问题发现也会写在这里，辛苦啦！

**Comment by Yurunsoft** [comment]
已经发版 v1.0.3，如果有问题可以再开 issue 反馈~

**Comment by bioinformatist** [comment]
好的！我已經替換啦！謝謝宇大！
