### ISSUE TITLE
3.0 url中tz配置无法填写

### ISSUE THREAD

**Issue by onlyshow** [Yurunsoft/tdengine-restful-connector#8]
[http://<fqdn>:<port>/rest/sql/[db_name][?tz=timezone]](https://docs.taosdata.com/connector/rest-api/#%E9%AA%8C%E8%AF%81)

**Comment by onlyshow** [comment]
能把yurunsoft/tdengine-orm中的yurunsoft/tdengine-restful-connector依赖版本更新下吗？

**Comment by Yurunsoft** [comment]
已发版
